version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "node-mysql"
s3_bucket = "hb-lambdabucket"
s3_prefix = "node-mysql"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"