version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "insurance-premium-calculation-function"
s3_bucket = "buckets4lambda"
s3_prefix = "insurance-premium-calculation-function"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
