AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda bucket-content-names function retrieves contents of a given bucket name through queryStringParameters

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  BucketContentNamesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: BucketContentNamesFunction
      Handler: bucketcontentnames.App::handleRequest
      Runtime: java8
      MemorySize: 512
      Role: arn:aws:iam::397178420157:role/Lambda_S3
      FunctionName: BucketContentNamesFunction
      #Environment: # More info about Env Vars: https://github
      #.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      #  Variables:
      #    PARAM1: VALUE
      # Give just CRUD permissions to this table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BucketContentTable
      Events:
        BucketContentNamesAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /all
            Method: get
  BucketContentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BucketContentsTable
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"
        - AttributeName: "CREATION_TIME"
          AttributeType: "S"
        #- AttributeName: "KEY_NAME"
        #  AttributeType: "S"
        #- AttributeName: "REQUEST_ID"
        #  AttributeType: "S"
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HASH" # Partition key
        - AttributeName: "CREATION_TIME"
          KeyType: "RANGE" # Sort key

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BucketContentNamesApi:
    Description: "API Gateway endpoint URL for Prod stage for BucketContentNames function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/all/"
  BucketContentNamesFunction:
    Description: "BucketContentNames Lambda Function ARN"
    Value: !GetAtt BucketContentNamesFunction.Arn
  BucketContentTableDynamo:
    Description: "The Dyanmo DB table to save bucket content names"
    Value: !GetAtt BucketContentTable.Arn
