AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:  lambda-send-sqs
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  SqsSendFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: lambda-send-sqs
      Role: arn:aws:iam::397178420157:role/LambdaSQSRole
      CodeUri: sqsSendFunction
      Handler: lambda.App::handleRequest
      Runtime: java11
      MemorySize: 512
      #Environment: # More info about Env Vars: https://github
      #.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
       # Variables:
        #  PARAM1: VALUE
      Events:
        sendSQS:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /send
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  sendSQSApi:
    Description: "API Gateway endpoint URL for Prod stage for send SQS message function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send/"
  sqsSendFunction:
    Description: "Send SQS message Lambda Function ARN"
    Value: !GetAtt SqsSendFunction.Arn
