AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Sample SAM Template for Java with MySql RDS connection.'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  JavaMysqlFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: javaMysql
      Handler: awssam.App::handleRequest
      Runtime: java8
      MemorySize: 512
      FunctionName: java-rds-mysql
      Description: Java app with RDS mysql connectivity.
      Role: arn:aws:iam::397178420157:role/lambda-vpc-role
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_HOST: hbdatabase.coalfqdle1sr.eu-west-2.rds.amazonaws.com
          DB_USER: admin
          DB_PASS: adminadmin
          DB_PORT: 3306
      Events:
        JavaMysqlApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      VpcConfig:
        SecurityGroupIds:
          - sg-b6b7a0d9
        SubnetIds:
          - subnet-ecaa64a0
          - subnet-bb64dcc1
          - subnet-32fd815b

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  JavaMysqlFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for JavaMysql function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  JavaMysqlFunction:
    Description: "JavaMysql Lambda Function ARN"
    Value: !GetAtt JavaMysqlFunction.Arn
  # Below creates a new role
  #JavaMysqlFunctionIamRole:
  #  Description: "Implicit IAM Role created for JavaMysql function"
  #  #Value: !GetAtt JavaMysqlFunction.Arn
