AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lambda-receive-sqs
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  SqsReceiveFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: lambda-receive-sqs
      Role: arn:aws:iam::397178420157:role/LambdaSQSRole
      CodeUri: sqsReceiveFunction
      Handler: lambda.App::handleRequest
      Runtime: java11
      MemorySize: 512
      #Environment: # More info about Env Vars: https://github
      #.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
       # Variables:
        #  PARAM1: VALUE
      Events:
        receiveSqs:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /receive
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  sqsReceiveApi:
    Description: "API Gateway endpoint URL for Prod stage for receiving SQS messages function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/receive/"
  sqsReceiveFunction:
    Description: "Receive SQS message Lambda Function ARN"
    Value: !GetAtt SqsReceiveFunction.Arn
