Description: Stack created by CDK with Java
Resources:
  CdkJavaHelloFunctionServiceRole66DA2F5E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloFunction/ServiceRole/Resource
  CdkJavaHelloFunctionServiceRoleDefaultPolicy73FEC758:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:ConditionCheckItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - cdkTablejava440D0D94
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: CdkJavaHelloFunctionServiceRoleDefaultPolicy73FEC758
      Roles:
        - Ref: CdkJavaHelloFunctionServiceRole66DA2F5E
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloFunction/ServiceRole/DefaultPolicy/Resource
  CdkJavaHelloFunction54F76B50:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersedaac38f2b34d2933341cfa1d9169e27fadb5369d3cc57cf9370ba7c4f4026e3S3BucketCC2BD723
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersedaac38f2b34d2933341cfa1d9169e27fadb5369d3cc57cf9370ba7c4f4026e3S3VersionKeyCB96826B
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersedaac38f2b34d2933341cfa1d9169e27fadb5369d3cc57cf9370ba7c4f4026e3S3VersionKeyCB96826B
      Role:
        Fn::GetAtt:
          - CdkJavaHelloFunctionServiceRole66DA2F5E
          - Arn
      Environment:
        Variables:
          DB_TABLE: cdkTable-java
      FunctionName: java-hello-cdk
      Handler: cdklambda.App::handleRequest
      Runtime: java11
    DependsOn:
      - CdkJavaHelloFunctionServiceRoleDefaultPolicy73FEC758
      - CdkJavaHelloFunctionServiceRole66DA2F5E
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloFunction/Resource
      aws:asset:path: /Users/hbez/myProjects/aws/cdk/cdk-java/lambdafunction/target/lambda-for-cdk-1.0.jar
      aws:asset:property: Code
  cdkTablejava440D0D94:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: cdkTable-java
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkJavaStack/cdkTable-java/Resource
  CdkJavaHelloApi942C2FAB:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Rest API created by CDK for NodeHelloFunction
      Name: CdkJavaHelloApi
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Resource
  CdkJavaHelloApiCloudWatchRoleAE73AD02:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/CloudWatchRole/Resource
  CdkJavaHelloApiAccount0BDDAAF1:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - CdkJavaHelloApiCloudWatchRoleAE73AD02
          - Arn
    DependsOn:
      - CdkJavaHelloApi942C2FAB
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Account
  CdkJavaHelloApiDeployment8ABDC766b78f30e4215e713d11904a5415d95d80:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: CdkJavaHelloApi942C2FAB
      Description: Automatically created by the RestApi construct
    DependsOn:
      - CdkJavaHelloApiGETF4B7B399
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Deployment/Resource
  CdkJavaHelloApiDeploymentStageprodF86F7DDE:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: CdkJavaHelloApi942C2FAB
      DeploymentId:
        Ref: CdkJavaHelloApiDeployment8ABDC766b78f30e4215e713d11904a5415d95d80
      StageName: prod
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/DeploymentStage.prod/Resource
  CdkJavaHelloApiGETApiPermissionCdkJavaStackCdkJavaHelloApi59121B34GET1FB8F561:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CdkJavaHelloFunction54F76B50
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-north-1:397178420157:"
            - Ref: CdkJavaHelloApi942C2FAB
            - /
            - Ref: CdkJavaHelloApiDeploymentStageprodF86F7DDE
            - /GET/
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Default/GET/ApiPermission.CdkJavaStackCdkJavaHelloApi59121B34.GET..
  CdkJavaHelloApiGETApiPermissionTestCdkJavaStackCdkJavaHelloApi59121B34GETCC57EA83:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CdkJavaHelloFunction54F76B50
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-north-1:397178420157:"
            - Ref: CdkJavaHelloApi942C2FAB
            - /test-invoke-stage/GET/
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Default/GET/ApiPermission.Test.CdkJavaStackCdkJavaHelloApi59121B34.GET..
  CdkJavaHelloApiGETF4B7B399:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Fn::GetAtt:
          - CdkJavaHelloApi942C2FAB
          - RootResourceId
      RestApiId:
        Ref: CdkJavaHelloApi942C2FAB
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:eu-north-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - CdkJavaHelloFunction54F76B50
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Default/GET/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAE02Q3U7EIBCFn8X7KWtj9sI76xovjMam+gJTGCtugYYfNw3h3QVqk72ab+BwODMtuz+y9uYBL67h4nyI3Fhi8cMjP0PnHPmMk9QTDORMsJzgZLTzNnAPpy/do0VFnmxp3oNfQj3exQmKcZxRjQJZfA6ae2l0kVxzT1ZJ53KXQKJicTAzVZ9SezNLvlZdpQTursGSzbEaEcSqURkxsviJ4/ayQv5+kRN6uuDK4mtNkaP5bpH/KXfsODdBe3iiZTarIl3HuOrKGqrxBvuAj+gI3sh/G1EuN0opwQv+4qE9stu83R8nZWOzvVTEhq3+Af7UWkV5AQAA
    Metadata:
      aws:cdk:path: CdkJavaStack/CDKMetadata/Default
Parameters:
  AssetParametersedaac38f2b34d2933341cfa1d9169e27fadb5369d3cc57cf9370ba7c4f4026e3S3BucketCC2BD723:
    Type: String
    Description: S3 bucket for asset "edaac38f2b34d2933341cfa1d9169e27fadb5369d3cc57cf9370ba7c4f4026e3"
  AssetParametersedaac38f2b34d2933341cfa1d9169e27fadb5369d3cc57cf9370ba7c4f4026e3S3VersionKeyCB96826B:
    Type: String
    Description: S3 key for asset version "edaac38f2b34d2933341cfa1d9169e27fadb5369d3cc57cf9370ba7c4f4026e3"
  AssetParametersedaac38f2b34d2933341cfa1d9169e27fadb5369d3cc57cf9370ba7c4f4026e3ArtifactHashED0A6272:
    Type: String
    Description: Artifact hash for asset "edaac38f2b34d2933341cfa1d9169e27fadb5369d3cc57cf9370ba7c4f4026e3"
Outputs:
  CdkJavaHelloApiEndpoint1F3D0DDC:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: CdkJavaHelloApi942C2FAB
          - .execute-api.eu-north-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: CdkJavaHelloApiDeploymentStageprodF86F7DDE
          - /

