Description: Stack created by CDK with Java
Resources:
  CdkJavaHelloFunctionServiceRole66DA2F5E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloFunction/ServiceRole/Resource
  CdkJavaHelloFunction54F76B50:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersfc98de1b7860c7135a3fdf1dee4e991312f4499689a40ce94d4a89ea9031f4f2S3Bucket66EE1C27
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersfc98de1b7860c7135a3fdf1dee4e991312f4499689a40ce94d4a89ea9031f4f2S3VersionKeyFB0E405E
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersfc98de1b7860c7135a3fdf1dee4e991312f4499689a40ce94d4a89ea9031f4f2S3VersionKeyFB0E405E
      Role:
        Fn::GetAtt:
          - CdkJavaHelloFunctionServiceRole66DA2F5E
          - Arn
      Environment:
        Variables:
          SOMEENV: SOMEVAR
      FunctionName: java-hello-cdk
      Handler: cdklambda.App::handleRequest
      Runtime: java11
    DependsOn:
      - CdkJavaHelloFunctionServiceRole66DA2F5E
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloFunction/Resource
      aws:asset:path: /Users/hbez/myProjects/aws/cdk/cdk-java/lambdafunction/target/lambda-for-cdk-1.0.jar
      aws:asset:property: Code
  CdkJavaHelloApi942C2FAB:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Rest API created by CDK for NodeHelloFunction
      Name: CdkJavaHelloApi
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Resource
  CdkJavaHelloApiCloudWatchRoleAE73AD02:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/CloudWatchRole/Resource
  CdkJavaHelloApiAccount0BDDAAF1:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - CdkJavaHelloApiCloudWatchRoleAE73AD02
          - Arn
    DependsOn:
      - CdkJavaHelloApi942C2FAB
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Account
  CdkJavaHelloApiDeployment8ABDC766b78f30e4215e713d11904a5415d95d80:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: CdkJavaHelloApi942C2FAB
      Description: Automatically created by the RestApi construct
    DependsOn:
      - CdkJavaHelloApiGETF4B7B399
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Deployment/Resource
  CdkJavaHelloApiDeploymentStageprodF86F7DDE:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: CdkJavaHelloApi942C2FAB
      DeploymentId:
        Ref: CdkJavaHelloApiDeployment8ABDC766b78f30e4215e713d11904a5415d95d80
      StageName: prod
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/DeploymentStage.prod/Resource
  CdkJavaHelloApiGETApiPermissionCdkJavaStackCdkJavaHelloApi59121B34GET1FB8F561:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CdkJavaHelloFunction54F76B50
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-north-1:397178420157:"
            - Ref: CdkJavaHelloApi942C2FAB
            - /
            - Ref: CdkJavaHelloApiDeploymentStageprodF86F7DDE
            - /GET/
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Default/GET/ApiPermission.CdkJavaStackCdkJavaHelloApi59121B34.GET..
  CdkJavaHelloApiGETApiPermissionTestCdkJavaStackCdkJavaHelloApi59121B34GETCC57EA83:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CdkJavaHelloFunction54F76B50
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-north-1:397178420157:"
            - Ref: CdkJavaHelloApi942C2FAB
            - /test-invoke-stage/GET/
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Default/GET/ApiPermission.Test.CdkJavaStackCdkJavaHelloApi59121B34.GET..
  CdkJavaHelloApiGETF4B7B399:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Fn::GetAtt:
          - CdkJavaHelloApi942C2FAB
          - RootResourceId
      RestApiId:
        Ref: CdkJavaHelloApi942C2FAB
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:eu-north-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - CdkJavaHelloFunction54F76B50
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Default/GET/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAE02QwU7DMBBEv4X7xiVCPXAjFHFAIKrwBYuzBNPYjrxrqsryv2MnROpp39irmbFbdb9X7c0DnrnRw2mXtA+k0oegPkHHTFJwNG6EntjHoAkO3rGEqAUOX+6IAS0JhSreo8xxOd6WM1TjNKH9HFCl5+i0GO/qyjUfKVjDXFQGg1al3k+0+JSZge8arFVYLY0AZzOi0BkvKr0u1iVPutn8R2/Yae2jE3iiefIXS27pdqXq25acFbbWj8gEbyTffqiXK+Wc4QV/cdfu1W35sh82pgnF3lhS/Tr/AKKPVHFOAQAA
    Metadata:
      aws:cdk:path: CdkJavaStack/CDKMetadata/Default
Parameters:
  AssetParametersfc98de1b7860c7135a3fdf1dee4e991312f4499689a40ce94d4a89ea9031f4f2S3Bucket66EE1C27:
    Type: String
    Description: S3 bucket for asset "fc98de1b7860c7135a3fdf1dee4e991312f4499689a40ce94d4a89ea9031f4f2"
  AssetParametersfc98de1b7860c7135a3fdf1dee4e991312f4499689a40ce94d4a89ea9031f4f2S3VersionKeyFB0E405E:
    Type: String
    Description: S3 key for asset version "fc98de1b7860c7135a3fdf1dee4e991312f4499689a40ce94d4a89ea9031f4f2"
  AssetParametersfc98de1b7860c7135a3fdf1dee4e991312f4499689a40ce94d4a89ea9031f4f2ArtifactHash7B2D85A4:
    Type: String
    Description: Artifact hash for asset "fc98de1b7860c7135a3fdf1dee4e991312f4499689a40ce94d4a89ea9031f4f2"
Outputs:
  CdkJavaHelloApiEndpoint1F3D0DDC:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: CdkJavaHelloApi942C2FAB
          - .execute-api.eu-north-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: CdkJavaHelloApiDeploymentStageprodF86F7DDE
          - /

