Description: Stack created by CDK with Java
Resources:
  CdkJavaHelloFunctionServiceRole66DA2F5E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloFunction/ServiceRole/Resource
  CdkJavaHelloFunctionServiceRoleDefaultPolicy73FEC758:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:ConditionCheckItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - cdkTablejava440D0D94
                  - Arn
              - Ref: AWS::NoValue
          - Action:
              - ssm:DescribeParameters
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParameterHistory
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - :ssm:eu-north-1:397178420157:parameter
                  - Ref: cdktestParamB796D4A0
        Version: "2012-10-17"
      PolicyName: CdkJavaHelloFunctionServiceRoleDefaultPolicy73FEC758
      Roles:
        - Ref: CdkJavaHelloFunctionServiceRole66DA2F5E
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloFunction/ServiceRole/DefaultPolicy/Resource
  CdkJavaHelloFunction54F76B50:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters9ebac80fe0a9ce3e14d25ff0c291e4b19c149777be7791afe3f6d456a619150fS3BucketF9E80D15
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9ebac80fe0a9ce3e14d25ff0c291e4b19c149777be7791afe3f6d456a619150fS3VersionKeyE0D5F927
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9ebac80fe0a9ce3e14d25ff0c291e4b19c149777be7791afe3f6d456a619150fS3VersionKeyE0D5F927
      Role:
        Fn::GetAtt:
          - CdkJavaHelloFunctionServiceRole66DA2F5E
          - Arn
      Description: Lambda function for AWS CDK
      Environment:
        Variables:
          DB_TABLE: cdkTable-java
          SSM_PARAM_NAME: /cdk/testParam
      FunctionName: CdkJavaFunction
      Handler: cdklambda.App::handleRequest
      MemorySize: 512
      Runtime: java11
      Timeout: 30
    DependsOn:
      - CdkJavaHelloFunctionServiceRoleDefaultPolicy73FEC758
      - CdkJavaHelloFunctionServiceRole66DA2F5E
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloFunction/Resource
      aws:asset:path: C:\Users\bezdj\IdeaProjects\aws\cdk\cdk-java-lambda-api\cdk.out\asset.9ebac80fe0a9ce3e14d25ff0c291e4b19c149777be7791afe3f6d456a619150f.jar
      aws:asset:property: Code
  cdkTablejava440D0D94:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: cdkTable-java
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkJavaStack/cdkTable-java/Resource
  CdkJavaHelloApi942C2FAB:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Rest API created by CDK for NodeHelloFunction
      Name: CdkJavaHelloApi
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Resource
  CdkJavaHelloApiCloudWatchRoleAE73AD02:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/CloudWatchRole/Resource
  CdkJavaHelloApiAccount0BDDAAF1:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - CdkJavaHelloApiCloudWatchRoleAE73AD02
          - Arn
    DependsOn:
      - CdkJavaHelloApi942C2FAB
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Account
  CdkJavaHelloApiDeployment8ABDC76641d7215a07a1f1dccca9121ea9108a51:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: CdkJavaHelloApi942C2FAB
      Description: Automatically created by the RestApi construct
    DependsOn:
      - CdkJavaHelloApiGETF4B7B399
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Deployment/Resource
  CdkJavaHelloApiDeploymentStageprodF86F7DDE:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: CdkJavaHelloApi942C2FAB
      DeploymentId:
        Ref: CdkJavaHelloApiDeployment8ABDC76641d7215a07a1f1dccca9121ea9108a51
      StageName: prod
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/DeploymentStage.prod/Resource
  CdkJavaHelloApiGETApiPermissionCdkJavaStackCdkJavaHelloApi59121B34GET1FB8F561:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CdkJavaHelloFunction54F76B50
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-north-1:397178420157:"
            - Ref: CdkJavaHelloApi942C2FAB
            - /
            - Ref: CdkJavaHelloApiDeploymentStageprodF86F7DDE
            - /GET/
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Default/GET/ApiPermission.CdkJavaStackCdkJavaHelloApi59121B34.GET..
  CdkJavaHelloApiGETApiPermissionTestCdkJavaStackCdkJavaHelloApi59121B34GETCC57EA83:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CdkJavaHelloFunction54F76B50
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-north-1:397178420157:"
            - Ref: CdkJavaHelloApi942C2FAB
            - /test-invoke-stage/GET/
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Default/GET/ApiPermission.Test.CdkJavaStackCdkJavaHelloApi59121B34.GET..
  CdkJavaHelloApiGETF4B7B399:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Fn::GetAtt:
          - CdkJavaHelloApi942C2FAB
          - RootResourceId
      RestApiId:
        Ref: CdkJavaHelloApi942C2FAB
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:eu-north-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - CdkJavaHelloFunction54F76B50
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Default/GET/Resource
  cdktestParamB796D4A0:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: cdk-test-param-value
      Description: SSM created by CDK-java
      Name: /cdk/testParam
    Metadata:
      aws:cdk:path: CdkJavaStack/--cdk--testParam/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02Q3U6EMBCFn2Xvy+yiid7KrvHCaCToCwxlxAptSX/ckIZ3ty0SuZozM83pN6eE8uYeTocHvNqCd8MxcG0IwrtDPrDKWnJR9kL17KKVdcZzxy6fqkaDkhwZ1pDV3nBK0zfvJp/323RhyTiMKNsOITx5xZ3QKj3Z65qMFNbGbmECJYRGj9kx11qPgs/5XVYLs7cFJjYLGTH2cPZ8IHdGS6ybFUrdtRA+sF19sogwk+jR0RVnCC+ZKYK6ahJ/zJusONdeOfZI06hnSSoftetSKNl4Fdu5+ftXcl+6S8tVRVwrU6Qmxvgf3D7FZVnYM/7gsbyDE5SHbytEYSKBkATNWn8B+3tDtqsBAAA=
    Metadata:
      aws:cdk:path: CdkJavaStack/CDKMetadata/Default
Parameters:
  AssetParameters9ebac80fe0a9ce3e14d25ff0c291e4b19c149777be7791afe3f6d456a619150fS3BucketF9E80D15:
    Type: String
    Description: S3 bucket for asset "9ebac80fe0a9ce3e14d25ff0c291e4b19c149777be7791afe3f6d456a619150f"
  AssetParameters9ebac80fe0a9ce3e14d25ff0c291e4b19c149777be7791afe3f6d456a619150fS3VersionKeyE0D5F927:
    Type: String
    Description: S3 key for asset version "9ebac80fe0a9ce3e14d25ff0c291e4b19c149777be7791afe3f6d456a619150f"
  AssetParameters9ebac80fe0a9ce3e14d25ff0c291e4b19c149777be7791afe3f6d456a619150fArtifactHash1BB731BF:
    Type: String
    Description: Artifact hash for asset "9ebac80fe0a9ce3e14d25ff0c291e4b19c149777be7791afe3f6d456a619150f"
Outputs:
  CdkJavaHelloApiEndpoint1F3D0DDC:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: CdkJavaHelloApi942C2FAB
          - .execute-api.eu-north-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: CdkJavaHelloApiDeploymentStageprodF86F7DDE
          - /
  LambdaServiceArn:
    Value:
      Fn::GetAtt:
        - CdkJavaHelloFunction54F76B50
        - Arn
  LambdaServiceUrl:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: CdkJavaHelloApi942C2FAB
          - .execute-api.eu-north-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: CdkJavaHelloApiDeploymentStageprodF86F7DDE
          - /

