AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  node-mysql

  Sample SAM Template for node-mysql

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  GetNamesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: Node-Mysql
      Role: arn:aws:iam::397178420157:role/lambda-vpc-role
      CodeUri: get-names/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        GetNames:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /names
            Method: post
      VpcConfig:
        SecurityGroupIds:
          - sg-b6b7a0d9
        SubnetIds:
          - subnet-bb64dcc1
          - subnet-32fd815b
          - subnet-ecaa64a0

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetNamesApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Names function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/names/"
  GetNamesFunction:
    Description: "Get Names Function ARN"
    Value: !GetAtt GetNamesFunction.Arn
  #GetNamesFunctionIamRole:
  #  Description: "Implicit IAM Role created for Get Names function"
  #  Value: !GetAtt GetNamesFunctionRole.Arn
