AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  insurance-premium-calculation-function

  Sample SAM Template for insurance-premium-calculation-function

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  InsuranceCalculationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: InsuranceCalculationFunction
      Handler: insurancecalculation.App::handleRequest
      Runtime: java11
      MemorySize: 512
      FunctionName: insurance-premium-calculation-function
      # Allow read on the DynamoDB table
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoDB
      Events:
        GetMonthlyCalculationEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /calculate
            Method: get
  # Create DynamoDB Table called InsuranceTariff
  DynamoDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: InsuranceTariff

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetMonthlyCalculationEventApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/calculate"
  InsuranceCalculationFunction:
    Description: "Insurance calculation function ARN"
    Value: !GetAtt InsuranceCalculationFunction.Arn