Description: Stack created by CDK with Java
Resources:
  CdkJavaHelloFunctionServiceRole66DA2F5E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloFunction/ServiceRole/Resource
  CdkJavaHelloFunctionServiceRoleDefaultPolicy73FEC758:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:ConditionCheckItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - cdkTablejava440D0D94
                  - Arn
              - Ref: AWS::NoValue
          - Action:
              - ssm:DescribeParameters
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParameterHistory
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - :ssm:eu-north-1:397178420157:parameter
                  - Ref: cdktestParamB796D4A0
        Version: "2012-10-17"
      PolicyName: CdkJavaHelloFunctionServiceRoleDefaultPolicy73FEC758
      Roles:
        - Ref: CdkJavaHelloFunctionServiceRole66DA2F5E
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloFunction/ServiceRole/DefaultPolicy/Resource
  CdkJavaHelloFunction54F76B50:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters7d0fa804cc004c1096207942534c489bf79ebe61a05b2bdee81483e3f66fd949S3Bucket72758758
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters7d0fa804cc004c1096207942534c489bf79ebe61a05b2bdee81483e3f66fd949S3VersionKey7E057F2A
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters7d0fa804cc004c1096207942534c489bf79ebe61a05b2bdee81483e3f66fd949S3VersionKey7E057F2A
      Role:
        Fn::GetAtt:
          - CdkJavaHelloFunctionServiceRole66DA2F5E
          - Arn
      Description: Lambda function for AWS CDK
      Environment:
        Variables:
          DB_TABLE: cdkTable-java
          SSM_PARAM_NAME: /cdk/testParam
      FunctionName: CdkJavaFunction
      Handler: cdklambda.App::handleRequest
      MemorySize: 512
      Runtime: java11
      Timeout: 30
    DependsOn:
      - CdkJavaHelloFunctionServiceRoleDefaultPolicy73FEC758
      - CdkJavaHelloFunctionServiceRole66DA2F5E
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloFunction/Resource
      aws:asset:path: /Users/hbez/myProjects/aws/cdk/cdk-java/lambdafunction/target/lambda-for-cdk-1.0.jar
      aws:asset:property: Code
  cdkTablejava440D0D94:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: cdkTable-java
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkJavaStack/cdkTable-java/Resource
  CdkJavaHelloApi942C2FAB:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Rest API created by CDK for NodeHelloFunction
      Name: CdkJavaHelloApi
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Resource
  CdkJavaHelloApiCloudWatchRoleAE73AD02:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/CloudWatchRole/Resource
  CdkJavaHelloApiAccount0BDDAAF1:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - CdkJavaHelloApiCloudWatchRoleAE73AD02
          - Arn
    DependsOn:
      - CdkJavaHelloApi942C2FAB
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Account
  CdkJavaHelloApiDeployment8ABDC76641d7215a07a1f1dccca9121ea9108a51:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: CdkJavaHelloApi942C2FAB
      Description: Automatically created by the RestApi construct
    DependsOn:
      - CdkJavaHelloApiGETF4B7B399
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Deployment/Resource
  CdkJavaHelloApiDeploymentStageprodF86F7DDE:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: CdkJavaHelloApi942C2FAB
      DeploymentId:
        Ref: CdkJavaHelloApiDeployment8ABDC76641d7215a07a1f1dccca9121ea9108a51
      StageName: prod
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/DeploymentStage.prod/Resource
  CdkJavaHelloApiGETApiPermissionCdkJavaStackCdkJavaHelloApi59121B34GET1FB8F561:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CdkJavaHelloFunction54F76B50
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-north-1:397178420157:"
            - Ref: CdkJavaHelloApi942C2FAB
            - /
            - Ref: CdkJavaHelloApiDeploymentStageprodF86F7DDE
            - /GET/
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Default/GET/ApiPermission.CdkJavaStackCdkJavaHelloApi59121B34.GET..
  CdkJavaHelloApiGETApiPermissionTestCdkJavaStackCdkJavaHelloApi59121B34GETCC57EA83:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CdkJavaHelloFunction54F76B50
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-north-1:397178420157:"
            - Ref: CdkJavaHelloApi942C2FAB
            - /test-invoke-stage/GET/
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Default/GET/ApiPermission.Test.CdkJavaStackCdkJavaHelloApi59121B34.GET..
  CdkJavaHelloApiGETF4B7B399:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Fn::GetAtt:
          - CdkJavaHelloApi942C2FAB
          - RootResourceId
      RestApiId:
        Ref: CdkJavaHelloApi942C2FAB
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:eu-north-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - CdkJavaHelloFunction54F76B50
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkJavaStack/CdkJavaHelloApi/Default/GET/Resource
  EC2SecurityG2279A886:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG created by CDK for EC2InstanceForCdk
      GroupName: EC2InstanceForCdk-SG
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Add SSH from anywhere
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      VpcId: vpc-4f569826
    Metadata:
      aws:cdk:path: CdkJavaStack/EC2SecurityG/Resource
  EC2InstanceCdk:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2}}"
      InstanceType: t3.micro
      SecurityGroupIds:
        - Fn::GetAtt:
            - EC2SecurityG2279A886
            - GroupId
      Tags:
        - Key: Name
          Value: EC2InstanceForCdk
    Metadata:
      aws:cdk:path: CdkJavaStack/EC2InstanceCdk
  cdktestParamB796D4A0:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: cdk-test-param-value
      Description: SSM created by CDK-java
      Name: /cdk/testParam
    Metadata:
      aws:cdk:path: CdkJavaStack/--cdk--testParam/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAE11Q0U7DMAz8lr2n2ToknilDIBCIqfADbuqNsCap4oSpivLvJClFgyffOfblfDWvN1u+Wd3AmSrRn9ZBGIs8vDkQJ9YQoUvwKPWRtUjGW4FsZzQ564Vju4PegwWFDm0mr96NvrSX4ciycBhAdT3wcO+1cNLoPHKJ92iVJEosMgmKh9YMWHRy3ZtBiqnMFRQZXVWQvREvFlk/aVCm73h4h27eLCB9P8ojODzDxMNzcZGsuWaUPy4X2AhhvHbsDsfBTAp1OeOC5RiK8AyWA2+BkL2g+zB9fpxRZCi2KUQU3ko3PVjjx7L6v/GYkgSdYyJSOXWbkv4T6S+JMbIn+IJ1fb36JCkrm+xKhbyd6zetwlnzygEAAA==
    Metadata:
      aws:cdk:path: CdkJavaStack/CDKMetadata/Default
Parameters:
  AssetParameters7d0fa804cc004c1096207942534c489bf79ebe61a05b2bdee81483e3f66fd949S3Bucket72758758:
    Type: String
    Description: S3 bucket for asset "7d0fa804cc004c1096207942534c489bf79ebe61a05b2bdee81483e3f66fd949"
  AssetParameters7d0fa804cc004c1096207942534c489bf79ebe61a05b2bdee81483e3f66fd949S3VersionKey7E057F2A:
    Type: String
    Description: S3 key for asset version "7d0fa804cc004c1096207942534c489bf79ebe61a05b2bdee81483e3f66fd949"
  AssetParameters7d0fa804cc004c1096207942534c489bf79ebe61a05b2bdee81483e3f66fd949ArtifactHash275A6AC7:
    Type: String
    Description: Artifact hash for asset "7d0fa804cc004c1096207942534c489bf79ebe61a05b2bdee81483e3f66fd949"
Outputs:
  CdkJavaHelloApiEndpoint1F3D0DDC:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: CdkJavaHelloApi942C2FAB
          - .execute-api.eu-north-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: CdkJavaHelloApiDeploymentStageprodF86F7DDE
          - /

