server:
  port: 5000

spring:
  application:
    name: aws-spring-app

management:
  endpoints:
    web:
      base-path: /admin
      path-mapping:
        health: healthcheck
  info:
    env:
      enabled: true