server:
  port: 5000

spring:
  datasource:
    name: AWS-RDS
    username: rds
    password: springbootapp
    url: jdbc:mysql://aa2mxhs51eyi1y.clrsxfhrhxie.eu-north-1.rds.amazonaws.com/ebdb
  application:
    name: aws-spring-app

management:
  endpoints:
    web:
      base-path: /admin
      path-mapping:
        health: healthcheck
  info:
    env:
      enabled: true