name: CI

on:
  push:
    branches: [ cdk-python-serverless-stack ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Source checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install aws-cdk
        run: sudo npm install -g aws-cdk

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Test
        run: pytest unittests

      - name: Bootstrap
        run: cdk bootstrap

      - name: CDK Deploy
        run: cdk deploy --require-approval=never --verbose

      - name: Integration test
        run: |
          export STACK_NAME=$(cdk ls)
          export ENDPOINT_URL=$(aws cloudformation describe-stacks \
              --stack-name $STACK_NAME \
              --query "Stacks[].Outputs[?OutputKey=='ApiGatewayUrl'].OutputValue" \
              --output text)
          echo $ENDPOINT_URL
          echo $STACK_NAME
          pytest integtests
          curl -Ssf $ENDPOINT_URL
